"""შეტყობინება

Revision ID: f360c82c0358
Revises: 
Create Date: 2020-11-04 18:35:52.707256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f360c82c0358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('geo_name', sa.String(), nullable=True),
    sa.Column('pic_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('pic', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['snakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finds')
    op.drop_table('snakes')
    # ### end Alembic commands ###
