"""added comments

Revision ID: 8f3d63c1a02a
Revises: 
Create Date: 2020-10-14 19:10:01.744215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3d63c1a02a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_model', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_model', 'comment')
    # ### end Alembic commands ###
