"""first migration

Revision ID: 493e8e704571
Revises: 
Create Date: 2020-10-23 20:28:40.581962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493e8e704571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
