"""v

Revision ID: ad9b12497182
Revises: 
Create Date: 2020-10-19 16:57:59.471088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9b12497182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_model', sa.Column('hair', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players_model', 'hair')
    # ### end Alembic commands ###
